### ISSUE TITLE
i18n spain, italian, russian, german & french

### ISSUE THREAD

**Issue by dutscher** [dutscher/trialstrackmap#1]
we need to translate the new winter tracks:

``` javascript
{
"135": "Walrus Road",
"136": "Snowman Haven",
"137": "Frostmoore",
"138": "Container Grounds",
"139": "Icy Foothills",
"140": "Frozen Facility",
"141": "Squall Slide",
"142": "Penguin Landing",
"143": "Ice Blockade",
"144": "Snowball Ride",
"145": "Sledridge Gorge",
"146": "Chopping District",
"149": "Icebound Hamlet",
"150": "Frosty Plumbing",
"151": "Permafrost Climb",
"152": "Chilled Cliffs"
}
```

148/152 [spain](https://github.com/dutscher/trialstrackmap/blob/master/database/i18n/es.json)
~~152/152 [italian](https://github.com/dutscher/trialstrackmap/blob/master/database/i18n/it.json)~~
~~152/152 [russian](https://github.com/dutscher/trialstrackmap/blob/master/database/i18n/ru.json)~~
~~152/152 [german](https://github.com/dutscher/trialstrackmap/blob/master/database/i18n/de.json)~~
~~152/152 [french](https://github.com/dutscher/trialstrackmap/blob/master/database/i18n/fr.json)~~

**Comment by Sergsavin** [comment]
in russian - 135  - Дорога моржей
136 - Убежище снеговиков
137 - Ледоград
138 - Земля коробок
139 - Ледяные предгорья
140 - Морозная служба
141 - Шквальное скольжение
142 - Пингвинье приземление

**Comment by dutscher** [comment]
thanks @Sergsavin, its commited and deployed! https://github.com/dutscher/trialstrackmap/commit/579e20b900a940202415a98a5a98e692c00d054e

**Comment by KevinFaussadier** [comment]
French : 
{
"135": "Route des morses",
"136": "Havre des bonhommes de neige",
"137": "Valgelé",
"138": "Aire des conteneurs",
"139": "Contreforts verglacés",
"140": "Complexe gelé",
"141": "Pente venteuse",
"142": "Aire aux pingouins",
"143": "Blocus de glace",
"144": "Montée des boules de neige",
"145": "Gorge de Lugeon",
"146": "Zone d'abattage"
}

**Comment by dutscher** [comment]
thanks @KevinFaussadier, its commited and deployed! https://github.com/dutscher/trialstrackmap/commit/7cca026ec9bfa8ba42219883af776b846de29001

**Comment by Sergsavin** [comment]
in russian new tracks:
{
"149": "Хижина во льдах",
"150": "Застывший водопровод",
"151": "Вымерзшая вершина",
"152": "Застывшие утесы"
}

**Comment by KevinFaussadier** [comment]
French 

{
"149": "Hameau givré",
"150": "Canalisations gelées",
"151": "Permagel",
"152": "Falaises transies"
}

**Comment by dutscher** [comment]
thanks @K3nya (ru)[https://github.com/dutscher/trialstrackmap/commit/a3ac1e0a2ed6f17b649d0fff0407026b9c490ebf], @Sergsavin (it)[https://github.com/dutscher/trialstrackmap/commit/4cb4865f3f997b03731fe195947bfb8e73f8c2d6] & @KevinFaussadier (fr)[https://github.com/dutscher/trialstrackmap/commit/a2407d5fc02e412ea02854fb53c24ce66dc90cb7], its commited and deployed!

**Comment by Vassagopk** [comment]
Spanish:

```
"149": "Villorio gélido",
"150": "Fontanería escarchada",
"151": "Cuesta permafrost",
"152": "Acantilados fresquitos"
```

**Comment by dutscher** [comment]
thanks @Vassagopk, its commited and deployed! https://github.com/dutscher/trialstrackmap/commit/5e292cdf70a7ae84f775a094a8a3a62dc57531ba
