### ISSUE TITLE
Acquirability of tracks

### ISSUE THREAD

**Issue by freaktechnik** [dutscher/trialstrackmap#38]
It would be nice if the track map indicated if, and how a track can be acquired. For some categories this is pretty obvious, like the lotz, bunker or story tracks. Same goes for the tracks you can only get in the loot wheel. But some event tracks were eventually added to the loot wheel, slot machine, daily deals, bunker season rewards etc.

**Comment by freaktechnik** [comment]
I've started to collect this information in https://github.com/freaktechnik/tf-track-sources

**Comment by dutscher** [comment]
hey martin, thanks for the suggestion.
but we use the categories for the acquirability http://trialstrackmap.sb-f.de/categories.html
but it also true that it is not intuitive visible for each track.

if you go to the table for all the tracks http://trialstrackmap.sb-f.de/table-medals.html#cat=1
you can filter the category and got all the tracks .

i think due this issue about a refactoring of the trackmap modal whats oppened if you click on a track.

i think about it :)

greetz

**Comment by freaktechnik** [comment]
I know that most of the tracks aquirability can be found out via categories. However that does not always reveal how the track is still acquirable if it was available as event reward, or for some of the tracks it is just missing (thinking of tracks like the KTM Track, which was available as bunker reward or in the daily deals)

**Comment by dutscher** [comment]
that's right i refactor the modal with more informations!
i see also in the forum that there are much threads about how i get this track and this.
maybe we could solve this!

p.s.: is this guy https://www.youtube.com/user/Jonnyswitzerland one of your family?

cheers

**Comment by freaktechnik** [comment]
Nice, let me know if I can be of help.

Don't know them, so not to my knowledge.

**Comment by dutscher** [comment]
hey martin, check out die new gallery modal http://trialstrackmap.sb-f.de/#track=ktm-course-210 for example this.
have i missed somtehing? i used your data to complete my categories.

what are these daily deals?

cheers

**Comment by freaktechnik** [comment]
Daily deals are the deals in the shopkeeper's shop that refresh every day. Those tracks are available there for some amount of diamonds, however I do not know if all of them are still in the rotation there, since I own all those tracks.

Very nice new modal!

**Comment by dutscher** [comment]
i see, i didnt get those daily deals :D because i got all the new tracks when RL released them.
Could you read all the informations? are they readable or handy? i need some feedback :)

Could you also check one random track if the data is complete?

Thanks for your input!

cheers

**Comment by freaktechnik** [comment]
You can find them mentioned i. Changelogs, which is what I recobstructed them from.

I've looked at a couple of tracks and I think it's at least a lot better. Maybe some way to tell whag chrrent and past sources are would be nice.

My data is pretty incomplete, as I've only added what I remember/know and what the changelogs I could find told me. I know for exampke that all the treasure hunt tracks were available by other means. And I recall something along the lines of the winter tracks being in the lootwheel.

I'm thinking aboht installing the game on a second phone and not logging ib to fibd iut all that.

**Comment by dutscher** [comment]
that can we do but its very time expensive.

we need the infos for those track your reach for a mission.
for example "dark machine", for this track you have get all data cubes (right?)
or "the purifier" (what we have todo for this track?).
for "great wall" we have to beat the chinese warrior for example.

are there any other tracks? 

cheers

**Comment by freaktechnik** [comment]
Isn't there casino rooftops that you get from seymore & lotz as the end of the quest chain?

Most of the "story" tracks are from cartographer missions for sure.

**Comment by freaktechnik** [comment]
I've now started with a brand new play-through and am noting down the quest tree. You can see the start of that in https://github.com/freaktechnik/tf-track-sources/commit/387f1fefa74006702a0f3c2e44a8154939a668c2 however it is not yet linked with track aquirability info.

**Comment by dutscher** [comment]
no hope to maintain this whole story. sorry for that but thanks for the hard work!
