### ISSUE TITLE
i18n (translation) of trackmap for improve and tracknames

### ISSUE THREAD

**Issue by dutscher** [dutscher/trialstrackmap#8]
- IT - italian (improve table, page, rodeo, halloween, christmas and KTM)
- FR - france (improve table, christmas and KTM)
- ES - spain (KTM)
- DE - german (christmas, KTM)

cheers

**Comment by Vassagopk** [comment]
"156": "Fábrica olvidada",

"158": "Peldaños baldíos",
"148": "Desde las rocas",
"159": "Escondite de villanos"

**Comment by dutscher** [comment]
gracias Vassagopk.

its merged https://github.com/dutscher/trialstrackmap/commit/19e1045d6636676da565d985ad03230f6da1f303

but missed one name for "Rigged Roadway" and

**Comment by Vassagopk** [comment]
"13": "Agentes"

Is Rigged Roadway the last track after you get all the blueprints? Because I already did that but I don't remember the name nor I know of any way to check it.

**Comment by dutscher** [comment]
yes i mean rigged roadway. i named it "carretera manipulado". make this sense in spanish?
and thanks for your help!

**Comment by Vassagopk** [comment]
It would be more like "Carretera amañada". But I was hoping to give you the exact translation. I guess this will do until we find a better one.

**Comment by Vassagopk** [comment]
"14": "Pack desafío 2",
    "15": "Rodeo Molón"

    #Change this one from the one you put from Google translate, it sounds better :)
    "157": "Carretera amañada",

    "160": "Carril de accidentes",
    "161": "Distrito de vigas",
    "162": "Plaza del especialista",
    "163": "Rito de paso",
    "164": "Alijo de mercancía",
    "165": "Tránsito engrasado",
    "166": "Huerto colapsado",
    "167": "Nido del cuervo",
    "168": "Campamento de vagabundos",
    "169": "Cantera de gemas",
    "170": "Pozo de diversión",
    "171": "Hogar tribal",
    "172": "Cosecha tóxica",
    "173": "El gran columpio"

**Comment by dutscher** [comment]
it's commited https://github.com/dutscher/trialstrackmap/commit/9f9e298af1a098be39ae876ae55d9b0437c46523 :) thanks vassagopk

**Comment by Vassagopk** [comment]
I've updated the spanish translation with all Halloween tracks, as well as some of the strings of the right sidebar. I edited the pastebin so you can copy and paste.

http://pastebin.com/9XzeJg2G

**Comment by Vassagopk** [comment]
Updated once again:

http://pastebin.com/9XzeJg2G

**Comment by dutscher** [comment]
thanks vassagopk and hue-br for translating! it's merged and deployed

**Comment by dutscher** [comment]
@Vassagopk please fork this project and make a pull request for the next translation :)

cheers

**Comment by dutscher** [comment]
now it's done with an import.
